import{S as d,i as c}from"./assets/vendor-5b791d57.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const m="https://pixabay.com",f="/api",g="/?key=42279202-5e6657fc85e4b10c09189e202&image_type=photo&orientation=horizontal&safesearch=true",y=m+f+g;function p(t){const i=t.trim();return i?fetch(y+`&q=${i}`):Promise.reject()}const s=document.querySelector("#search-input"),u=document.querySelector("#gallery"),h=document.querySelector(".loader"),v=document.querySelector(".navigation"),a={searchInput:s,gallery:u,loader:h,navigationForm:v},L=new d("#gallery .gallery-item .gallery-link ",{dowload:!1,close:!0,closeText:"×",captions:!0,captionsData:"alt",captionType:"attr",captionDelay:250,captionSelector:"img"});function S(){b(),p(s.value).then(t=>t.json()).then(t=>{P(t.hits);const i=t.hits.map(o=>`<div class="gallery-item">
        <a class="gallery-link" href="${o.largeImageURL}">
            <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}" />
        </a>
        <div class="image-info">
            <div>Likes: ${o.likes}</div>
            <div>Views: ${o.views}</div>
            <div>Comments: ${o.comments}</div>
            <div>Downloads: ${o.downloads}</div>
        </div>
        </div>`).join("");u.innerHTML=i,L.refresh()}).catch(()=>{c.show({message:'"Sorry, there are no images matching your search query. Please try again!"',position:"topRight",title:"",color:"red"})}).finally(()=>{w()}),s.value=""}function b(){a.loader.style.display="inline-block"}function w(){a.loader.style.display="none"}function P(t){t.length||c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",title:"",color:"red"})}a.navigationForm.addEventListener("submit",t=>{t.preventDefault(),S()});
//# sourceMappingURL=commonHelpers.js.map
